### ISSUE TITLE
:zap: Scenario Reduction Algorithm -> Barrier with epsilon never works 

### ISSUE THREAD

**Issue by MxHbm** [MxHbm/Management-Science#10]
In the original paper the introduced epsilon doesn't have a function 

--> Important to remember for Beleg!

**Comment by b4ghir1** [comment]
From my point of view, epsilon have to be an integer value, so that it can' be a float.:
![Bildschirmfoto vom 2024-05-06 10-32-32](https://github.com/MxHbm/Management-Science/assets/52173490/d42ab2df-3a39-48ed-9b06-d7f21cdca3a6)


And if this is the output of calculation:
`print(f'{i}, f_scenario: {self._N} * {self._p_base_scenarios[i]} = {f_scenario}')`
 
![Bildschirmfoto vom 2024-05-06 10-22-18](https://github.com/MxHbm/Management-Science/assets/52173490/f7d81f2b-358a-441c-be9c-b7073965ecb0)

Epsilon have to be something like [1, 12, 26, .....]. I guess we can experiment a bit to find a good epsilon value.

**Comment by MxHbm** [comment]
ja das weiß ich schon haha, aber **im Paper nutzen** sie 0,001. Das kommt dann bisschen weiter unten

**Comment by MxHbm** [comment]
Deswegen ist das ein fail von denen, und wir sollten das nennen, aber zum nachbilden der Daten 0,001 nutzen

**Comment by b4ghir1** [comment]
![Bildschirmfoto vom 2024-05-06 14-21-52](https://github.com/MxHbm/Management-Science/assets/52173490/22f388df-4f3d-488e-858b-6a21c2304c0d)

ah, okay. :D 
Das muss ich später noch mal händisch nachvollziehen ^^

**Comment by b4ghir1** [comment]
--> alle Szenarien werden in die Cluster-Analyse mit einbezogen, deswegen ist 0.0001 auch okay.

**Comment by b4ghir1** [comment]
(Römisch - Scenario Reduction: vorwärts oder rückwärts Reduktion. 
Szenariobasierte Verfahren bei Modellierung mit Unsicherheit -> Szenario

Sample Average Approximation
-> systematischer Ansatz um Szenarien auszuwählen, Fehlerterm bestimmbar

**Comment by MxHbm** [comment]
auch geklärt in Konsultation
